version: "3"
name: "Ajay-Dhangar"
services:
    serve:
        build:
            context: .
            target: serve
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=production
