
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
    community: [
      {
        type: 'autogenerated',
        dirName: '.',
      },
      {
        type: 'link',
        href: '/',
        label: 'Changelog',
      },
      {
        type: 'link',
        href: '/',
        label: 'Showcase',
      },
      {
        type: 'link',
        href: '/',
        label: 'Feature Requests',
      },
      {
        type: 'link',
        label: 'Chat with us',
        href: '#',
      },
    ],
  };