
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {  
  tutorialSidebar: [  
    {
      type: 'autogenerated', 
      dirName: '.',
    }
  ],
  // api: [{type: 'autogenerated',dirName: 'api',}],
  // communitySidebar: ['doc3', 'doc4'],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
