name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          Thanks for opening an issue in CodeHarborHub! 🚀
          We'll get back to you as soon as possible.
        pr-message: >
          Thanks for opening a pull request in CodeHarborHub! 🎉
          We appreciate your contribution and will review it shortly.
